version: '3.8'
services:
  app:
    build: .
    ports:
      - "5001:5001"
    environment:
      - DATABASE_URI=postgresql://postgres:exaple@db:5432/trading_db
      - JWT_SECRET_KEY=yourjwtsecret_kay
    depends_on:
      - db
      - redis
      - rabbitmq
    networks:
      - backend

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=trading_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:latest
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres_data: